DROP TABLE "INQUIRY" CASCADE CONSTRAINTS;
DROP TABLE "REPORT" CASCADE CONSTRAINTS;
DROP TABLE "FAQ" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE P_REG CASCADE CONSTRAINTS;
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "WISHLIST" CASCADE CONSTRAINTS;
DROP TABLE "CARD" CASCADE CONSTRAINTS;
DROP TABLE "ADDRESS" CASCADE CONSTRAINTS;
DROP TABLE "SALE" CASCADE CONSTRAINTS;
DROP TABLE "ACCOUNT" CASCADE CONSTRAINTS;
DROP TABLE "EVENT" CASCADE CONSTRAINTS;
DROP TABLE "PRICE_CHART" CASCADE CONSTRAINTS;
DROP TABLE "TRADE" CASCADE CONSTRAINTS;
DROP TABLE "P_IMG" CASCADE CONSTRAINTS;
DROP TABLE "BID" CASCADE CONSTRAINTS;
DROP TABLE "SALE_IMG" CASCADE CONSTRAINTS;
DROP TABLE "CARDINFO" CASCADE CONSTRAINTS;


CREATE TABLE "INQUIRY" (
	"INQUIRY_NO"	NUMBER		NOT NULL,
	"INQUIRY_WRITER"	NUMBER		NOT NULL,
	"INQUIRY_CATEGORY_BIG"	VARCHAR2(30)		NOT NULL,
	"INQUIRY_CATEGORY_SMALL"	VARCHAR2(30)		NOT NULL,
	"INQUIRY_TITLE"	VARCHAR2(200)		NOT NULL,
	"INQUIRY_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"INQUIRY_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"INQUIRY_STATUS"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"INQUIRY_ANSWER"	VARCHAR2(4000)		NULL,
	"INQUIRY_ANSWER_DATE"	DATE		NULL
);

COMMENT ON COLUMN "INQUIRY"."INQUIRY_WRITER" IS '작성자';

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"SALE_NO"	NUMBER		NOT NULL,
	"REPORT_WRTIER"	NUMBER		NOT NULL,
	"REPORT_CATEGORY"	VARCHAR2(30)		NOT NULL,
	"REPORT_TITLE"	VARCHAR2(200)		NOT NULL,
	"REPORT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REPORT_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REPORT_STATUS"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_WRTIER" IS '신고자';



CREATE TABLE "FAQ" (
	"FAQ_NO"	NUMBER		NOT NULL,
	"FAQ_CATEGORY"	VARCHAR2(40)		NOT NULL,
	"FAQ_TITLE"	VARCHAR2(200)		NOT NULL,
	"FAQ_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"FAQ_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);



CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(200)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"NOTICE_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTICE_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);



CREATE TABLE P_REG (
	"PR_NO"	NUMBER		NOT NULL,
	"PR_IMAGE"	VARCHAR2(300)		NOT NULL,
	"PR_MODEL"	VARCHAR2(100)		NOT NULL,
	"PR_NAME"	VARCHAR2(100)		NOT NULL,
	"PR_CATEGORY"	VARCHAR2(100)		NOT NULL,
	"PR_BRAND"	VARCHAR2(100)		NOT NULL,
	"PR_SIZE"	VARCHAR2(100)		NULL,
	"PR_COLOR"	VARCHAR2(100)		NOT NULL,
	"PR_REVIEW_YOUTUBE"	VARCHAR2(300)		NULL,
	"PR_REVIEW_DETAIL"	VARCHAR2(4000)		NULL,
	"PR_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PR_RELEASE_DATE"	DATE		NOT NULL,
	"PR_RELEASE_PRICE"	NUMBER		NOT NULL,
	"PR_HITS"	NUMBER	DEFAULT 0	NOT NULL,
	"PR_STATUS"	VARCHAR(1)	DEFAULT 'Y'	NOT NULL
);



CREATE TABLE "MEMBER" (
	"MEM_USER_NO"	NUMBER		NOT NULL,
	"MEM_USER_ID"	VARCHAR2(30)		NOT NULL,
	"MEM_USER_PWD"	VARCHAR2(30)		NOT NULL,
	"MEM_USER_NAME"	VARCHAR2(30)		NOT NULL,
	"MEM_PHONE"	VARCHAR2(30)		NOT NULL,
	"MEM_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEM_MODIFY_DATE"	DATE		NULL,
	"MEM_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"MEM_USER_SSN"	VARCHAR2(30)		NULL,
	"MEM_OUT_DATE"	DATE		NULL,
	"MEM_REPORT_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_BLACKLIST_STATUS"	VARCHAR(1)	DEFAULT 'N'	NOT NULL
);



CREATE TABLE "WISHLIST" (
	"WISHLIST_PCODE"	NUMBER		NOT NULL,
	"WISHLIST_MCODE"	NUMBER		NOT NULL,
	"WISHLIST_ADD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);



CREATE TABLE "CARD" (
	"CARD_NO"	NUMBER		NOT NULL,
	"MEM_USER_NO"	NUMBER		NOT NULL,
	"CARD_NAME"	VARCHAR2(30)		NOT NULL,
	"CARD_NUMBER"	VARCHAR2(30)		NOT NULL,
	"CARD_VALIDATE"	VARCHAR2(10)		NOT NULL,
	"CARD_MEM_BIRTH"	VARCHAR2(30)		NOT NULL,
	"CARD_PWD"	NUMBER		NOT NULL,
	"CARDINFO_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CARD"."CARD_NO" IS 'PK';

COMMENT ON COLUMN "CARD"."MEM_USER_NO" IS 'FK';

COMMENT ON COLUMN "CARD"."CARD_VALIDATE" IS 'YY-MM';

COMMENT ON COLUMN "CARD"."CARDINFO_NO" IS 'FK';



CREATE TABLE "ADDRESS" (
	"ADDRESS_NO"	NUMBER		NOT NULL,
	"MEM_USER_NO"	NUMBER		NOT NULL,
	"ADDRESS_CODE"	NUMBER		NOT NULL,
	"ADDRESS_MAIN"	VARCHAR2(100)		NOT NULL,
	"ADDRESS_DETAIL"	VARCHAR2(100)		NOT NULL,
	"ADDRESS_PHONE"	VARCHAR2(30)		NOT NULL,
	"ADDRESS_NAME"	VARCHAR2(30)		NOT NULL,
	"ADDRESS_BASIC"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"ADDRESS_MESSAGE"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "ADDRESS"."ADDRESS_NO" IS 'PK';

COMMENT ON COLUMN "ADDRESS"."MEM_USER_NO" IS 'FK';

COMMENT ON COLUMN "ADDRESS"."ADDRESS_BASIC" IS 'Y/N';



CREATE TABLE "ACCOUNT" (
	"ACCOUNT_NO"	NUMBER		NOT NULL,
	"MEM_USER_NO"	NUMBER		NOT NULL,
	"ACCOUNT_BACKNAME"	VARCHAR2(30)		NOT NULL,
	"ACCOUNT_NUMBER"	VARCHAR2(30)		NOT NULL,
	"ACCOUNT_HOLDER"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "ACCOUNT"."ACCOUNT_HOLDER" IS '예금주명 = 회원명';



CREATE TABLE "SALE" (
	"SALE_NO"	NUMBER		NOT NULL,
	"PR_NO"	NUMBER		NOT NULL,
	"MEM_USER_NO"	NUMBER		NOT NULL,
	"SALE_PRICE"	NUMBER		NOT NULL,
	"SALE_NAME"	VARCHAR2(40)		NOT NULL,
	"SALE_ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"SALE_CONDITION"	VARCHAR2(10)		NOT NULL,
	"SALE_STATUS"	VARCHAR2(20)	DEFAULT '거래 전'	NOT NULL,
	"SALE_SIZE"	VARCHAR2(20)		NULL,
	"SALE_CATEGORY"	VARCHAR2(20)		NOT NULL,
	"SALE_PERIOD"	VARCHAR2(20)		NOT NULL,
	"SALE_BOX_STATUS"	VARCHAR2(1)		NOT NULL
);

COMMENT ON COLUMN "SALE"."MEM_USER_NO" IS '판매자';

COMMENT ON COLUMN "SALE"."SALE_PRICE" IS '판매자 등록 가격';

COMMENT ON COLUMN "SALE"."SALE_ENROLL_DATE" IS 'YY-MM-DD';

COMMENT ON COLUMN "SALE"."SALE_CONDITION" IS 'NEW/USED';

COMMENT ON COLUMN "SALE"."SALE_STATUS" IS '거래 전/거래 중/거래 완료';

COMMENT ON COLUMN "SALE"."SALE_BOX_STATUS" IS 'S/A/B/F';



CREATE TABLE "PRICE_CHART" (
	"PC_NO"	NUMBER		NOT NULL,
	"PC_PRICE"	NUMBER		NOT NULL,
	"PC_MONTH_PRICE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PRICE_CHART"."PC_NO" IS '제품번호';



CREATE TABLE "EVENT" (
	"EVENT_NO"	NUMBER		NOT NULL,
	"EVENT_IMAGE"	VARCHAR2(100)		NOT NULL,
	"EVENT_DETAIL"	VARCHAR2(100)		NOT NULL,
	"EVENT_STATUS"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "EVENT"."EVENT_NO" IS '이벤트 게시판 번호';

COMMENT ON COLUMN "EVENT"."EVENT_IMAGE" IS '이벤트 게시판 이미지';

COMMENT ON COLUMN "EVENT"."EVENT_DETAIL" IS '이벤트 게시판 설명';

COMMENT ON COLUMN "EVENT"."EVENT_STATUS" IS 'Y/N';


CREATE TABLE "P_IMG" (
	"PR_IMG_NO"	NUMBER		NOT NULL,
	"PR_NO"	NUMBER		NOT NULL,
	"PR_IMG_URL"	VARCHAR2(100)		NULL
);



CREATE TABLE "SALE_IMG" (
	"SALE_IMG_NO"	NUMBER		NOT NULL,
	"SALE_NO"	NUMBER		NOT NULL,
	"SALE_IMG_URL"	VARCHAR2(100)		NULL
);



CREATE TABLE "TRADE" (
	"TRADE_NO"	NUMBER		NOT NULL,
	"SALE_NO"	NUMBER		NOT NULL,
	"MEM_USER_NO"	NUMBER		NOT NULL,
	"ADDRESS_NO"	NUMBER		NOT NULL,
	"TRADE_STATUS"	VARCHAR2(20)	DEFAULT '배송전'	NOT NULL,
	"TRADE_SERVICE"	VARCHAR2(10)		NULL,
	"TRADE_NUMBER"	NUMBER		NULL,
	"TRADE_CONCLUDE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TRADE_END"	DATE		NULL,
	"TRADE_PRICE"	NUMBER		NOT NULL,
	"BID_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "TRADE"."MEM_USER_NO" IS '구매자';

COMMENT ON COLUMN "TRADE"."ADDRESS_NO" IS 'PK';

COMMENT ON COLUMN "TRADE"."TRADE_STATUS" IS '배송전/배송중/배송완료';

COMMENT ON COLUMN "TRADE"."TRADE_PRICE" IS '구매가격';



CREATE TABLE "BID" (
	"BID_NO"	NUMBER		NOT NULL,
	"SALE_NO"	NUMBER		NOT NULL,
	"MEM_USER_NO"	NUMBER		NOT NULL,
	"BID_PRICE"	NUMBER		NOT NULL,
	"BID_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ADDRESS_NO"	NUMBER		NOT NULL,
	"BID_STATUS"	VARCHAR2(20)	DEFAULT '경매중'	NOT NULL
);

COMMENT ON COLUMN "BID"."SALE_NO" IS '거래번호';

COMMENT ON COLUMN "BID"."MEM_USER_NO" IS '구매자';

COMMENT ON COLUMN "BID"."BID_DATE" IS 'YY-MM-DD-HH-mm';

COMMENT ON COLUMN "BID"."ADDRESS_NO" IS 'PK';

COMMENT ON COLUMN "BID"."BID_STATUS" IS '경매중/경매완료';



CREATE TABLE "CARDINFO" (
	"CARDINFO_NO"	NUMBER		NOT NULL,
	"CARDINFO_NAME"	VARCHAR2(30)		NOT NULL,
	"CARDINFO_IMG_URL"	VARCHAR2(100)		NOT NULL
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY (
	"INQUIRY_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY (
	"FAQ_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "P_REG" ADD CONSTRAINT "PK_P_REG" PRIMARY KEY (
	"PR_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEM_USER_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"WISHLIST_PCODE",
	"WISHLIST_MCODE"
);

ALTER TABLE "CARD" ADD CONSTRAINT "PK_CARD" PRIMARY KEY (
	"CARD_NO"
);

ALTER TABLE "ADDRESS" ADD CONSTRAINT "PK_ADDRESS" PRIMARY KEY (
	"ADDRESS_NO"
);

ALTER TABLE "ACCOUNT" ADD CONSTRAINT "PK_ACCOUNT" PRIMARY KEY (
	"ACCOUNT_NO"
);

ALTER TABLE "SALE" ADD CONSTRAINT "PK_SALE" PRIMARY KEY (
	"SALE_NO"
);

ALTER TABLE "PRICE_CHART" ADD CONSTRAINT "PK_PRICE_CHART" PRIMARY KEY (
	"PC_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EVENT_NO"
);

ALTER TABLE "P_IMG" ADD CONSTRAINT "PK_P_IMG" PRIMARY KEY (
	"PR_IMG_NO"
);

ALTER TABLE "SALE_IMG" ADD CONSTRAINT "PK_SALE_IMG" PRIMARY KEY (
	"SALE_IMG_NO"
);

ALTER TABLE "TRADE" ADD CONSTRAINT "PK_TRADE" PRIMARY KEY (
	"TRADE_NO"
);

ALTER TABLE "BID" ADD CONSTRAINT "PK_BID" PRIMARY KEY (
	"BID_NO"
);

ALTER TABLE "CARDINFO" ADD CONSTRAINT "PK_CARDINFO" PRIMARY KEY (
	"CARDINFO_NO"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_1" FOREIGN KEY (
	"INQUIRY_WRITER"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_SALE_TO_REPORT_1" FOREIGN KEY (
	"SALE_NO"
)
REFERENCES "SALE" (
	"SALE_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"REPORT_WRTIER"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_P_REG_TO_WISHLIST_1" FOREIGN KEY (
	"WISHLIST_PCODE"
)
REFERENCES "P_REG" (
	"PR_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEMBER_TO_WISHLIST_1" FOREIGN KEY (
	"WISHLIST_MCODE"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "CARD" ADD CONSTRAINT "FK_MEMBER_TO_CARD_1" FOREIGN KEY (
	"MEM_USER_NO"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "CARD" ADD CONSTRAINT "FK_CARDINFO_TO_CARD_1" FOREIGN KEY (
	"CARDINFO_NO"
)
REFERENCES "CARDINFO" (
	"CARDINFO_NO"
);

ALTER TABLE "ADDRESS" ADD CONSTRAINT "FK_MEMBER_TO_ADDRESS_1" FOREIGN KEY (
	"MEM_USER_NO"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "ACCOUNT" ADD CONSTRAINT "FK_MEMBER_TO_ACCOUNT_1" FOREIGN KEY (
	"MEM_USER_NO"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "SALE" ADD CONSTRAINT "FK_P_REG_TO_SALE_1" FOREIGN KEY (
	"PR_NO"
)
REFERENCES "P_REG" (
	"PR_NO"
);

ALTER TABLE "SALE" ADD CONSTRAINT "FK_MEMBER_TO_SALE_1" FOREIGN KEY (
	"MEM_USER_NO"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "PRICE_CHART" ADD CONSTRAINT "FK_SALE_TO_PRICE_CHART_1" FOREIGN KEY (
	"PC_NO"
)
REFERENCES "SALE" (
	"SALE_NO"
);

ALTER TABLE "P_IMG" ADD CONSTRAINT "FK_P_REG_TO_P_IMG_1" FOREIGN KEY (
	"PR_NO"
)
REFERENCES "P_REG" (
	"PR_NO"
);

ALTER TABLE "SALE_IMG" ADD CONSTRAINT "FK_SALE_TO_SALE_IMG_1" FOREIGN KEY (
	"SALE_NO"
)
REFERENCES "SALE" (
	"SALE_NO"
);

ALTER TABLE "TRADE" ADD CONSTRAINT "FK_SALE_TO_TRADE_1" FOREIGN KEY (
	"SALE_NO"
)
REFERENCES "SALE" (
	"SALE_NO"
);

ALTER TABLE "TRADE" ADD CONSTRAINT "FK_MEMBER_TO_TRADE_1" FOREIGN KEY (
	"MEM_USER_NO"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "TRADE" ADD CONSTRAINT "FK_ADDRESS_TO_TRADE_1" FOREIGN KEY (
	"ADDRESS_NO"
)
REFERENCES "ADDRESS" (
	"ADDRESS_NO"
);

ALTER TABLE "TRADE" ADD CONSTRAINT "FK_BID_TO_TRADE_1" FOREIGN KEY (
	"BID_NO"
)
REFERENCES "BID" (
	"BID_NO"
);

ALTER TABLE "BID" ADD CONSTRAINT "FK_SALE_TO_BID_1" FOREIGN KEY (
	"SALE_NO"
)
REFERENCES "SALE" (
	"SALE_NO"
);

ALTER TABLE "BID" ADD CONSTRAINT "FK_MEMBER_TO_BID_1" FOREIGN KEY (
	"MEM_USER_NO"
)
REFERENCES "MEMBER" (
	"MEM_USER_NO"
);

ALTER TABLE "BID" ADD CONSTRAINT "FK_ADDRESS_TO_BID_1" FOREIGN KEY (
	"ADDRESS_NO"
)
REFERENCES "ADDRESS" (
	"ADDRESS_NO"
);
